import fs from 'node:fs/promises';
import path from 'node:path';
import { execute } from '../server/local.mjs';
const apps=['Devin','Cursor','Visual Studio Code','Claude','ChatGPT','LM Studio','Docker','Xcode','Developer'];
const result={time:new Date().toISOString(),applications:[],cli:[],scope:'Installed development applications and known coding CLIs; versions are not account/E2E proof.'};
for(const name of apps){const plist=path.join('/Applications',name+'.app/Contents/Info.plist');try{await fs.access(plist);const r=await execute('/usr/bin/plutil',['-extract','CFBundleShortVersionString','raw','-o','-',plist],{timeout:5000});result.applications.push({name,path:path.dirname(path.dirname(plist)),version:r.stdout.trim(),status:r.code===0?'installed':'version-unverified'});}catch{result.applications.push({name,status:'not_found'});}}
const cli=[['OpenCode',`${process.env.HOME}/.opencode/bin/opencode`],['Claude Code',`${process.env.HOME}/.npm-global/bin/claude`],['Claude Code native',`${process.env.HOME}/.local/bin/claude`],['Codex','/Applications/ChatGPT.app/Contents/Resources/codex'],['Cursor Agent',`${process.env.HOME}/.local/bin/agent`],['Cline',`${process.env.HOME}/.npm-global/bin/cline`],['Goose',`${process.env.HOME}/.local/bin/goose`],['Grok',`${process.env.HOME}/.grok/bin/grok`],['OpenClaw',`${process.env.HOME}/.nvm/versions/node/v24.15.0/bin/openclaw`]];
for(const [name,binary]of cli){try{await fs.access(binary);const r=await execute(binary,['--version'],{cwd:'/private/tmp',timeout:8000,env:{...process.env,DISABLE_AUTO_UPDATE:'1',NO_COLOR:'1'}});const item={name,path:binary,version:r.stdout.trim().slice(0,200),status:r.code===0?'version-pass':r.timedOut?'timeout':'error',stderr:r.stderr.trim().slice(0,200)};result.cli.push(item);console.log(JSON.stringify(item));}catch{result.cli.push({name,path:binary,status:'not_found'});}}
await fs.writeFile('evidence/system-inventory.json',JSON.stringify(result,null,2));console.log(JSON.stringify({applications:result.applications,receipt:'evidence/system-inventory.json'}));
