#!/bin/bash
# D1 to PostgreSQL Migration Script
# Converts SQLite D1 exports to PostgreSQL-compatible SQL.
# Usage: ./scripts/d1-to-postgres.sh <d1_export.json> <output.sql>

set -euo pipefail

INPUT="${1:-}"
OUTPUT="${2:-./.data/d1-migration.sql}"

if [[ -z "$INPUT" ]]; then
  echo "Usage: $0 <d1_export.json> [output.sql]"
  echo "  d1_export.json: Exported D1 database from Cloudflare API"
  echo "  output.sql:     PostgreSQL-compatible output file"
  exit 1
fi

echo "=== D1 to PostgreSQL Migration ==="
echo "Input:  $INPUT"
echo "Output: $OUTPUT"
echo ""

mkdir -p "$(dirname "$OUTPUT")"

# Header
cat > "$OUTPUT" << 'EOF'
-- D1 to PostgreSQL Migration
-- Auto-generated by d1-to-postgres.sh
-- WARNING: Review before execution. Some SQLite features require manual adjustment.

SET search_path TO omdala, public;

EOF

# Extract tables and data from D1 export
# D1 export format is JSON with SQL statements
if command -v jq &> /dev/null; then
  echo "[1/2] Extracting schema..."
  jq -r '.result // .tables // [] | .[] | select(.type == "table") | .sql' "$INPUT" 2>/dev/null | sed \
    -e 's/INTEGER PRIMARY KEY AUTOINCREMENT/SERIAL PRIMARY KEY/g' \
    -e 's/INTEGER PRIMARY KEY/BIGINT PRIMARY KEY/g' \
    -e 's/TEXT/VARCHAR(255)/g' \
    -e 's/REAL/DOUBLE PRECISION/g' \
    -e 's/BLOB/BYTEA/g' \
    -e 's/DATETIME/TIMESTAMP/g' \
    -e 's/"\([^"]*\)"/\1/g' \
    >> "$OUTPUT" || true

  echo "[2/2] Extracting data..."
  jq -r '.result // .tables // [] | .[] | select(.type == "table") | .name' "$INPUT" 2>/dev/null | while read -r TABLE; do
    echo "-- Data for table: $TABLE" >> "$OUTPUT"
    jq -r --arg table "$TABLE" '.result // .tables // [] | .[] | select(.name == $table and .type == "table") | .data // [] | .[] | to_entries | map(.value) | @csv' "$INPUT" 2>/dev/null | sed 's/^/COPY '$TABLE' FROM STDIN CSV;\n/' >> "$OUTPUT" || true
  done
else
  echo "jq not found. Using basic sed conversion..."
  sed -e 's/INTEGER PRIMARY KEY AUTOINCREMENT/SERIAL PRIMARY KEY/g' \
      -e 's/INTEGER PRIMARY KEY/BIGINT PRIMARY KEY/g' \
      -e 's/TEXT/VARCHAR(255)/g' \
      -e 's/REAL/DOUBLE PRECISION/g' \
      "$INPUT" >> "$OUTPUT"
fi

# Footer
cat >> "$OUTPUT" << 'EOF'

-- Migration complete
-- Run: psql -U omdala_migration -d omdala_prod -f this_file.sql
EOF

echo ""
echo "=== Migration SQL Generated ==="
echo "File: $OUTPUT"
echo ""
echo "Next steps:"
echo "  1. Review $OUTPUT for manual adjustments (JSON columns, indexes, triggers)"
echo "  2. Test on staging database: make migrate"
echo "  3. Run on production only after approval gate"
