name = "omdala-api"
main = "src/index.ts"
compatibility_date = "2026-03-17"
account_id = "f3f9e76222dcb488d5e303e29e8ba192"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[dev]
port = 8789

[env.staging]
name = "omdala-api-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
