-- Rollback: AI Omniverse Core Schema
BEGIN;
DROP TABLE IF EXISTS device_templates CASCADE;
DROP TABLE IF EXISTS omniverse_subscriptions CASCADE;
DROP TABLE IF EXISTS home_invites CASCADE;
DROP TABLE IF EXISTS home_members CASCADE;
DROP TABLE IF EXISTS activity_log CASCADE;
DROP TABLE IF EXISTS automations CASCADE;
DROP TABLE IF EXISTS scenes CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS rooms CASCADE;
DROP TABLE IF EXISTS homes CASCADE;
COMMIT;
