import type { OmdalaLanguage } from "@omdala/core";
import {
  pickBilingualValue,
  resolveLanguageFromSearchParams,
  type BilingualValue,
  type SearchParamsInput,
} from "@omdala/ui";

type AwaitableSearchParams =
  | Promise<Record<string, string | string[] | undefined> | undefined>
  | Record<string, string | string[] | undefined>
  | undefined;

export function t(language: OmdalaLanguage, value: BilingualValue): string {
  return pickBilingualValue(language, value);
}

export async function resolvePageLanguage(
  searchParams?: AwaitableSearchParams,
): Promise<OmdalaLanguage> {
  const resolved = searchParams ? await searchParams : undefined;
  return resolveLanguageFromSearchParams(
    (resolved ?? null) as SearchParamsInput,
  );
}

export const APP_COPY = {
  shared: {
    on: { en: "On", vi: "Bật" },
    off: { en: "Off", vi: "Tắt" },
    system: { en: "System", vi: "Hệ thống" },
    light: { en: "Light", vi: "Sáng" },
    dark: { en: "Dark", vi: "Tối" },
    save: { en: "Save", vi: "Lưu" },
    cancel: { en: "Cancel", vi: "Hủy" },
    noData: { en: "No data", vi: "Chưa có dữ liệu" },
    none: { en: "None", vi: "Không có" },
    unknown: { en: "Unknown", vi: "Không xác định" },
  },
  layout: {
    fallbackEyebrow: {
      en: "Session Check",
      vi: "Kiểm tra phiên",
    },
    fallbackTitle: {
      en: "Preparing dashboard shell...",
      vi: "Đang chuẩn bị bảng điều khiển...",
    },
    productSurface: {
      en: "Product Surface",
      vi: "Bề mặt sản phẩm",
    },
    appNavigation: {
      en: "App navigation",
      vi: "Điều hướng ứng dụng",
    },
    navLabels: {
      Dashboard: { en: "Dashboard", vi: "Bảng điều khiển" },
      Nodes: { en: "Nodes", vi: "Nút" },
      Resources: { en: "Resources", vi: "Tài nguyên" },
      Trust: { en: "Trust", vi: "Niềm tin" },
      Offers: { en: "Offers", vi: "Đề nghị" },
      Requests: { en: "Requests", vi: "Nhu cầu" },
      Profile: { en: "Profile", vi: "Hồ sơ" },
      Settings: { en: "Settings", vi: "Cài đặt" },
    },
  },
  authGate: {
    eyebrow: {
      en: "Session Check",
      vi: "Kiểm tra phiên",
    },
    title: {
      en: "Checking your operator session...",
      vi: "Đang kiểm tra phiên vận hành...",
    },
    body: {
      en: "Redirecting to login if the current session is missing or expired.",
      vi: "Sẽ chuyển sang đăng nhập nếu phiên hiện tại bị thiếu hoặc đã hết hạn.",
    },
  },
  dashboard: {
    eyebrow: {
      en: "Operations dashboard",
      vi: "Bảng điều khiển vận hành",
    },
    welcomePrefix: {
      en: "Welcome back",
      vi: "Chào mừng trở lại",
    },
    intro: {
      en: "The app currently runs on a structured mock data flow where trust scores, matching hints, notifications, and AI actions are connected in one operational graph.",
      vi: "Ứng dụng hiện đang chạy trên luồng dữ liệu mẫu có cấu trúc, nơi điểm niềm tin, gợi ý ghép nối, thông báo và hành động AI đều được nối vào cùng một đồ thị vận hành.",
    },
    stats: {
      session: {
        title: { en: "Session", vi: "Phiên đăng nhập" },
        body: {
          en: "Passwordless auth has loaded role-aware operator context.",
          vi: "Lớp đăng nhập không mật khẩu đã nạp đầy đủ bối cảnh vận hành theo vai trò.",
        },
      },
      primaryRole: { en: "Primary role", vi: "Vai trò chính" },
      primaryNode: { en: "Primary node", vi: "Nút chính" },
      noData: { en: "No data", vi: "Chưa có dữ liệu" },
      activeNodes: {
        title: { en: "Active nodes", vi: "Nút đang hoạt động" },
        suffix: {
          en: "nodes are currently active in the sample operation graph.",
          vi: "nút đang hiện diện trong đồ thị vận hành mẫu.",
        },
      },
      resourceFlow: {
        title: { en: "Resource flow", vi: "Luồng tài nguyên" },
        suffix: {
          en: "resources are ready for trust operations and matching.",
          vi: "tài nguyên đang sẵn sàng cho vận hành niềm tin và ghép nối.",
        },
      },
      pendingProofs: {
        title: { en: "Pending proofs", vi: "Bằng chứng chờ duyệt" },
        suffix: {
          en: "items need review before wider distribution.",
          vi: "mục cần được rà soát trước khi mở rộng phân phối.",
        },
      },
      highPriorityAi: {
        title: { en: "High-priority AI actions", vi: "Hành động AI ưu tiên cao" },
        suffix: {
          en: "actions are currently marked high priority.",
          vi: "hành động đang được gắn mức ưu tiên cao.",
        },
      },
    },
    coreWorkspace: {
      title: { en: "Core workspace", vi: "Khu vực làm việc cốt lõi" },
      openNodes: { en: "Open nodes", vi: "Mở nút" },
      openResources: { en: "Open resources", vi: "Mở tài nguyên" },
      openTrust: { en: "Open trust", vi: "Mở niềm tin" },
      openOffers: { en: "Open offers", vi: "Mở đề nghị" },
      openRequests: { en: "Open requests", vi: "Mở nhu cầu" },
    },
    trustSummary: {
      title: {
        en: "Primary node trust summary",
        vi: "Tóm tắt niềm tin của nút chính",
      },
      level: { en: "Level", vi: "Mức độ" },
      score: { en: "Score", vi: "Điểm số" },
      highlights: { en: "Highlights", vi: "Điểm mạnh" },
      blockers: { en: "Blockers", vi: "Điểm cần xử lý" },
      band: { en: "Band", vi: "Dải đánh giá" },
    },
    matching: {
      title: { en: "Recommended matching", vi: "Ghép nối nên làm tiếp" },
      openNextStep: { en: "Open next step", vi: "Mở bước tiếp theo" },
    },
    updates: {
      eyebrow: { en: "Updates", vi: "Hộp cập nhật" },
      title: { en: "Notifications", vi: "Thông báo" },
    },
    aiLayer: {
      eyebrow: { en: "AI Layer", vi: "Lớp AI" },
      title: { en: "Suggested actions", vi: "Hành động được đề xuất" },
      topSuggestionPrefix: {
        en: "Top suggestion",
        vi: "Gợi ý nổi bật nhất",
      },
      confidenceSuffix: {
        en: "confidence",
        vi: "độ tin cậy",
      },
      openAction: {
        en: "Open action",
        vi: "Mở hành động",
      },
    },
  },
  trustPage: {
    eyebrow: {
      en: "Trust layer",
      vi: "Lớp niềm tin",
    },
    title: {
      en: "Trust operations workspace",
      vi: "Không gian vận hành niềm tin",
    },
    intro: {
      en: "This workspace brings node trust, resource trust, and proof queue priorities together so review and activation happen on one operational surface.",
      vi: "Màn hình này gom niềm tin của nút, niềm tin của tài nguyên và mức ưu tiên của hàng chờ bằng chứng để việc rà duyệt và kích hoạt diễn ra trên cùng một bề mặt vận hành.",
    },
    nodeTrustTable: {
      en: "Node trust table",
      vi: "Bảng niềm tin của nút",
    },
    resourceTrustTable: {
      en: "Resource trust table",
      vi: "Bảng niềm tin của tài nguyên",
    },
    proofLabel: {
      en: "proofs",
      vi: "bằng chứng",
    },
    proofQueueTitle: {
      en: "Proof review queue",
      vi: "Hàng chờ rà duyệt bằng chứng",
    },
    proofStatusPrefix: {
      en: "Status",
      vi: "Trạng thái",
    },
    proofPriorityPrefix: {
      en: "Priority",
      vi: "Ưu tiên",
    },
    nextActionsTitle: {
      en: "Recommended next actions",
      vi: "Hành động nên làm tiếp",
    },
    addProofAction: {
      en: "Add proof for resources",
      vi: "Bổ sung bằng chứng cho tài nguyên",
    },
    reviewNodeAction: {
      en: "Review node readiness",
      vi: "Rà soát độ sẵn sàng của nút",
    },
    backToDashboard: {
      en: "Back to dashboard",
      vi: "Quay lại bảng điều khiển",
    },
    statusVerified: {
      en: "Verified",
      vi: "Đã xác minh",
    },
    statusPending: {
      en: "Pending review",
      vi: "Đang chờ duyệt",
    },
    statusNotStarted: {
      en: "Not started",
      vi: "Chưa bắt đầu",
    },
  },
  nodes: {
    list: {
      eyebrow: { en: "Node layer", vi: "Lớp nút vận hành" },
      title: { en: "Nodes", vi: "Các nút" },
      intro: {
        en: "Nodes are currently backed by a structured operation graph where identity, trust score, resource density, and matching hints converge on one surface.",
        vi: "Các nút hiện được nâng đỡ bởi một đồ thị vận hành có cấu trúc, nơi danh tính, điểm niềm tin, mật độ tài nguyên và gợi ý ghép nối hội tụ trên cùng một bề mặt.",
      },
      create: { en: "Create node", vi: "Tạo nút mới" },
      location: { en: "Location", vi: "Địa điểm" },
      resources: { en: "Resources", vi: "Tài nguyên" },
      offers: { en: "Offers", vi: "Đề nghị" },
      openRequests: { en: "Open requests", vi: "Nhu cầu đang mở" },
      readiness: { en: "Readiness", vi: "Độ sẵn sàng" },
      status: { en: "Status", vi: "Trạng thái" },
      viewDetail: { en: "View details", vi: "Xem chi tiết" },
      edit: { en: "Edit", vi: "Chỉnh sửa" },
    },
    form: {
      breadcrumbRoot: { en: "Nodes", vi: "Nút" },
      breadcrumbNew: { en: "New", vi: "Mới" },
      breadcrumbEdit: { en: "Edit", vi: "Chỉnh sửa" },
      newEyebrow: { en: "Create node", vi: "Tạo nút" },
      newTitle: { en: "New node draft", vi: "Bản nháp nút mới" },
      newIntro: {
        en: "This form locks the node-creation fields before persistence is wired to real backend services.",
        vi: "Biểu mẫu này khóa các trường của luồng tạo nút trước khi persistence được nối với backend thật.",
      },
      editEyebrow: { en: "Edit node", vi: "Chỉnh sửa nút" },
      name: { en: "Name", vi: "Tên" },
      slug: { en: "Slug", vi: "Slug" },
      nodeType: { en: "Node type", vi: "Loại nút" },
      primaryRole: { en: "Primary role", vi: "Vai trò chính" },
      summary: { en: "Summary", vi: "Tóm tắt" },
      location: { en: "Location", vi: "Địa điểm" },
      visibility: { en: "Visibility", vi: "Mức hiển thị" },
      namePlaceholder: { en: "Node name", vi: "Tên nút" },
      slugPlaceholder: { en: "node-slug", vi: "node-slug" },
      summaryPlaceholder: {
        en: "Shortly describe this node and its operational purpose.",
        vi: "Mô tả ngắn về nút và mục đích hoạt động.",
      },
      locationPlaceholder: {
        en: "City, country, or remote",
        vi: "Thành phố, quốc gia hoặc từ xa",
      },
      saveDraft: { en: "Save draft", vi: "Lưu bản nháp" },
      saveChanges: { en: "Save changes", vi: "Lưu thay đổi" },
      archive: { en: "Archive node", vi: "Lưu trữ nút" },
      cancel: { en: "Cancel", vi: "Hủy" },
    },
    detail: {
      breadcrumbRoot: { en: "Nodes", vi: "Nút" },
      location: { en: "Location", vi: "Địa điểm" },
      verification: { en: "Verification", vi: "Xác minh" },
      linkedResources: { en: "Linked resources", vi: "Tài nguyên liên kết" },
      edit: { en: "Edit node", vi: "Chỉnh sửa nút" },
      viewResources: { en: "View resources", vi: "Xem tài nguyên" },
      trustEyebrow: { en: "Trust", vi: "Niềm tin" },
      matchingEyebrow: { en: "Matching", vi: "Ghép nối" },
      score: { en: "Score", vi: "Điểm số" },
      highlights: { en: "Highlights", vi: "Điểm mạnh" },
      blockers: { en: "Blockers", vi: "Điểm cần xử lý" },
    },
  },
  offers: {
    list: {
      eyebrow: { en: "Offer layer", vi: "Lớp đề nghị" },
      title: { en: "Offers", vi: "Đề nghị" },
      intro: {
        en: "Offers currently run on seeded relations between node ownership, linked resources, and trust-backed readiness scores.",
        vi: "Các đề nghị hiện chạy trên những quan hệ dữ liệu đã được gieo sẵn giữa quyền sở hữu nút, tài nguyên liên kết và điểm sẵn sàng có niềm tin hậu thuẫn.",
      },
      create: { en: "Create offer", vi: "Tạo đề nghị" },
      minimumTrust: { en: "Minimum trust", vi: "Niềm tin tối thiểu" },
      ownerNode: { en: "Owner node", vi: "Nút sở hữu" },
      pricing: { en: "Pricing", vi: "Định giá" },
      linkedResources: { en: "Linked resources", vi: "Tài nguyên liên kết" },
      proofDensity: { en: "Proof density", vi: "Mật độ bằng chứng" },
      readiness: { en: "Readiness", vi: "Độ sẵn sàng" },
      viewDetail: { en: "View details", vi: "Xem chi tiết" },
      edit: { en: "Edit", vi: "Chỉnh sửa" },
      status: {
        draft: { en: "Draft", vi: "Nháp" },
        published: { en: "Published", vi: "Đang mở" },
        paused: { en: "Paused", vi: "Tạm dừng" },
        archived: { en: "Archived", vi: "Đã lưu trữ" },
      },
    },
    form: {
      breadcrumbRoot: { en: "Offers", vi: "Đề nghị" },
      breadcrumbNew: { en: "New", vi: "Mới" },
      breadcrumbEdit: { en: "Edit", vi: "Chỉnh sửa" },
      newEyebrow: { en: "Create offer", vi: "Tạo đề nghị" },
      newTitle: { en: "New offer draft", vi: "Bản nháp đề nghị mới" },
      newIntro: {
        en: "This form locks the minimum structure for publishing value from a node and related resources.",
        vi: "Biểu mẫu này khóa cấu trúc tối thiểu để xuất bản giá trị từ một nút và các tài nguyên liên quan.",
      },
      editEyebrow: { en: "Edit offer", vi: "Chỉnh sửa đề nghị" },
      nodeId: { en: "Node ID", vi: "Mã nút" },
      resourceIds: { en: "Resource IDs", vi: "Mã tài nguyên" },
      title: { en: "Title", vi: "Tiêu đề" },
      slug: { en: "Slug", vi: "Slug" },
      category: { en: "Category", vi: "Danh mục" },
      summary: { en: "Summary", vi: "Tóm tắt" },
      pricingMode: { en: "Pricing mode", vi: "Kiểu định giá" },
      visibility: { en: "Visibility", vi: "Mức hiển thị" },
      minimumTrust: { en: "Minimum trust level", vi: "Mức niềm tin tối thiểu" },
      resourceIdsPlaceholder: {
        en: "resource-a, resource-b",
        vi: "resource-a, resource-b",
      },
      categoryPlaceholder: {
        en: "Consulting, hosting, workshop...",
        vi: "Tư vấn, tiếp đón, workshop...",
      },
      saveDraft: { en: "Save draft", vi: "Lưu bản nháp" },
      saveChanges: { en: "Save changes", vi: "Lưu thay đổi" },
      archive: { en: "Archive offer", vi: "Lưu trữ đề nghị" },
      cancel: { en: "Cancel", vi: "Hủy" },
      trustNone: { en: "No requirement", vi: "Không yêu cầu" },
    },
    detail: {
      breadcrumbRoot: { en: "Offers", vi: "Đề nghị" },
      minimumTrust: { en: "Minimum trust", vi: "Niềm tin tối thiểu" },
      ownerNode: { en: "Owner node", vi: "Nút sở hữu" },
      pricing: { en: "Pricing", vi: "Định giá" },
      resourceIds: { en: "Resource IDs", vi: "Mã tài nguyên" },
      edit: { en: "Edit offer", vi: "Chỉnh sửa đề nghị" },
    },
  },
  requests: {
    list: {
      eyebrow: { en: "Request layer", vi: "Lớp nhu cầu" },
      title: { en: "Requests", vi: "Nhu cầu" },
      intro: {
        en: "Requests currently use seeded matching context combining owner-node mappings and candidate-offer density to prioritize execution.",
        vi: "Các nhu cầu hiện dùng bối cảnh ghép nối đã được gieo sẵn, kết hợp ánh xạ nút sở hữu và mật độ đề nghị ứng viên để ưu tiên luồng thực thi.",
      },
      create: { en: "Create request", vi: "Tạo nhu cầu" },
      urgency: { en: "Urgency", vi: "Mức khẩn" },
      ownerNode: { en: "Owner node", vi: "Nút sở hữu" },
      budgetHint: { en: "Budget hint", vi: "Gợi ý ngân sách" },
      candidateOffers: { en: "Candidate offers", vi: "Đề nghị ứng viên" },
      matchingReadiness: { en: "Matching readiness", vi: "Độ sẵn sàng ghép nối" },
      viewDetail: { en: "View details", vi: "Xem chi tiết" },
      edit: { en: "Edit", vi: "Chỉnh sửa" },
    },
    form: {
      breadcrumbRoot: { en: "Requests", vi: "Nhu cầu" },
      breadcrumbNew: { en: "New", vi: "Mới" },
      breadcrumbEdit: { en: "Edit", vi: "Chỉnh sửa" },
      newEyebrow: { en: "Create request", vi: "Tạo nhu cầu" },
      newTitle: { en: "New request draft", vi: "Bản nháp nhu cầu mới" },
      newIntro: {
        en: "This form defines the minimum structure before request persistence is connected to backend services.",
        vi: "Biểu mẫu này xác định cấu trúc tối thiểu cho nhu cầu đi vào trước khi backend persistence được nối vào.",
      },
      editEyebrow: { en: "Edit request", vi: "Chỉnh sửa nhu cầu" },
      nodeId: { en: "Node ID", vi: "Mã nút" },
      title: { en: "Title", vi: "Tiêu đề" },
      slug: { en: "Slug", vi: "Slug" },
      category: { en: "Category", vi: "Danh mục" },
      summary: { en: "Summary", vi: "Tóm tắt" },
      urgency: { en: "Urgency", vi: "Mức khẩn" },
      visibility: { en: "Visibility", vi: "Mức hiển thị" },
      budgetHint: { en: "Budget hint", vi: "Gợi ý ngân sách" },
      saveDraft: { en: "Save draft", vi: "Lưu bản nháp" },
      saveChanges: { en: "Save changes", vi: "Lưu thay đổi" },
      archive: { en: "Archive request", vi: "Lưu trữ nhu cầu" },
      cancel: { en: "Cancel", vi: "Hủy" },
    },
    detail: {
      breadcrumbRoot: { en: "Requests", vi: "Nhu cầu" },
      urgency: { en: "Urgency", vi: "Mức khẩn" },
      ownerNode: { en: "Owner node", vi: "Nút sở hữu" },
      budgetHint: { en: "Budget hint", vi: "Gợi ý ngân sách" },
      edit: { en: "Edit request", vi: "Chỉnh sửa nhu cầu" },
    },
  },
  resources: {
    list: {
      eyebrow: { en: "Resource layer", vi: "Lớp tài nguyên" },
      title: { en: "Resources", vi: "Tài nguyên" },
      intro: {
        en: "Resources currently flow through one trust and matching pipeline. Each card surfaces ownership context, trust score, and activation hints for next steps.",
        vi: "Tài nguyên hiện đi qua cùng một pipeline niềm tin và ghép nối. Mỗi thẻ hiển thị bối cảnh sở hữu, điểm niềm tin và gợi ý kích hoạt cho bước kế tiếp.",
      },
      create: { en: "Create resource", vi: "Tạo tài nguyên" },
      ownerNode: { en: "Owner node", vi: "Nút sở hữu" },
      visibility: { en: "Visibility", vi: "Mức hiển thị" },
      proofCount: { en: "Proof count", vi: "Số bằng chứng" },
      trustScore: { en: "Trust score", vi: "Điểm niềm tin" },
      viewDetail: { en: "View details", vi: "Xem chi tiết" },
      edit: { en: "Edit", vi: "Chỉnh sửa" },
    },
    form: {
      breadcrumbRoot: { en: "Resources", vi: "Tài nguyên" },
      breadcrumbNew: { en: "New", vi: "Mới" },
      breadcrumbEdit: { en: "Edit", vi: "Chỉnh sửa" },
      newEyebrow: { en: "Create resource", vi: "Tạo tài nguyên" },
      newTitle: { en: "New resource draft", vi: "Bản nháp tài nguyên mới" },
      newIntro: {
        en: "This form locks the resource creation flow before persistence and data validation are connected.",
        vi: "Biểu mẫu này khóa luồng tạo bản ghi tài nguyên trước khi persistence và xác thực dữ liệu được nối vào.",
      },
      editEyebrow: { en: "Edit resource", vi: "Chỉnh sửa tài nguyên" },
      nodeId: { en: "Node ID", vi: "Mã nút" },
      title: { en: "Title", vi: "Tiêu đề" },
      slug: { en: "Slug", vi: "Slug" },
      resourceType: { en: "Resource type", vi: "Loại tài nguyên" },
      description: { en: "Description", vi: "Mô tả" },
      availabilityMode: { en: "Availability mode", vi: "Kiểu khả dụng" },
      pricingMode: { en: "Pricing mode", vi: "Kiểu định giá" },
      visibility: { en: "Visibility", vi: "Mức hiển thị" },
      titlePlaceholder: { en: "Resource title", vi: "Tiêu đề tài nguyên" },
      slugPlaceholder: { en: "resource-slug", vi: "resource-slug" },
      descriptionPlaceholder: {
        en: "Describe the resource clearly.",
        vi: "Mô tả tài nguyên một cách rõ ràng.",
      },
      saveDraft: { en: "Save draft", vi: "Lưu bản nháp" },
      saveChanges: { en: "Save changes", vi: "Lưu thay đổi" },
      archive: { en: "Archive resource", vi: "Lưu trữ tài nguyên" },
      cancel: { en: "Cancel", vi: "Hủy" },
    },
    detail: {
      breadcrumbRoot: { en: "Resources", vi: "Tài nguyên" },
      ownerNode: { en: "Owner node", vi: "Nút sở hữu" },
      visibility: { en: "Visibility", vi: "Mức hiển thị" },
      utilizationHint: { en: "Utilization hint", vi: "Gợi ý khai thác" },
      edit: { en: "Edit resource", vi: "Chỉnh sửa tài nguyên" },
      viewOwnerNode: { en: "View owner node", vi: "Xem nút sở hữu" },
      trustEyebrow: { en: "Trust", vi: "Niềm tin" },
      matchingEyebrow: { en: "Matching", vi: "Ghép nối" },
      score: { en: "Score", vi: "Điểm số" },
      highlights: { en: "Highlights", vi: "Điểm mạnh" },
      blockers: { en: "Blockers", vi: "Điểm cần xử lý" },
    },
  },
  profile: {
    eyebrow: { en: "Account Profile", vi: "Hồ sơ tài khoản" },
    intro: {
      en: "Profile is now the Team 1 entry point for shared account/profile contracts. It should map to",
      vi: "Hồ sơ hiện là điểm vào của Team 1 cho các ràng buộc dùng chung về tài khoản và hồ sơ. Nó cần ánh xạ tới",
    },
    introSuffix: {
      en: "and stay independent from Omniverse domain data.",
      vi: "và phải tách biệt khỏi dữ liệu miền Omniverse.",
    },
    identity: { en: "Account identity", vi: "Định danh tài khoản" },
    boundary: { en: "Profile and preference boundary", vi: "Ranh giới hồ sơ và tùy chọn" },
    route: { en: "Update contract route", vi: "Đường dẫn cập nhật hồ sơ" },
    routeCopy: {
      en: "Profile updates write through",
      vi: "Cập nhật hồ sơ được ghi qua",
    },
    routeMiddle: {
      en: "as Team 1 source-of-truth. Preferences stay in Settings via",
      vi: "như nguồn dữ liệu chuẩn của Team 1. Tùy chọn vẫn nằm trong phần Cài đặt qua",
    },
    routeSuffix: {
      en: "to keep account and billing boundaries clean.",
      vi: "để giữ ranh giới giữa tài khoản và thanh toán luôn rõ ràng.",
    },
    email: { en: "Email", vi: "Email" },
    timezone: { en: "Timezone", vi: "Múi giờ" },
    locale: { en: "Locale", vi: "Ngôn ngữ vùng" },
    roles: { en: "Roles", vi: "Vai trò" },
    sessionExpiry: { en: "Session expiry", vi: "Thời điểm hết hạn phiên" },
    theme: { en: "Theme", vi: "Giao diện" },
    language: { en: "Language", vi: "Ngôn ngữ" },
    emailNotifications: { en: "Email notifications", vi: "Thông báo qua email" },
    pushNotifications: { en: "Push notifications", vi: "Thông báo đẩy" },
    rolesMap: {
      expert: { en: "expert", vi: "chuyên gia" },
      host: { en: "host", vi: "điểm đón" },
      community: { en: "community", vi: "cộng đồng" },
      business: { en: "business", vi: "doanh nghiệp" },
      admin: { en: "admin", vi: "quản trị viên" },
      system: { en: "system", vi: "hệ thống" },
    },
  },
  profileFlow: {
    title: { en: "Profile update flow", vi: "Luồng cập nhật hồ sơ" },
    displayName: { en: "Display name", vi: "Tên hiển thị" },
    bio: { en: "Bio", vi: "Tiểu sử" },
    timezone: { en: "Timezone", vi: "Múi giờ" },
    locale: { en: "Locale", vi: "Ngôn ngữ vùng" },
    save: { en: "Save profile contract", vi: "Lưu cập nhật hồ sơ" },
    saving: { en: "Saving...", vi: "Đang lưu..." },
    success: {
      en: "Profile contract update completed.",
      vi: "Đã hoàn tất cập nhật hồ sơ.",
    },
    failure: {
      en: "Unable to update profile contract.",
      vi: "Không thể cập nhật hồ sơ.",
    },
  },
  settings: {
    eyebrow: { en: "Settings Runtime", vi: "Lớp vận hành cài đặt" },
    settings: { en: "Settings", vi: "Cài đặt" },
    intro: {
      en: "Settings is the control surface for preferences, subscription visibility, and usage metering. It should align to",
      vi: "Cài đặt là bề mặt điều khiển cho tùy chọn, mức hiển thị gói và đo lường mức sử dụng. Nó cần khớp với",
    },
    introSuffix: { en: "contracts.", vi: "các ràng buộc này." },
    languageMode: { en: "Language mode", vi: "Chế độ ngôn ngữ" },
    currentPlan: { en: "Current plan", vi: "Gói hiện tại" },
    betaGate: { en: "Beta gate", vi: "Cổng beta" },
    statusIs: { en: "with status", vi: "với trạng thái" },
    dailyUsage: { en: "Daily usage", vi: "Mức sử dụng hằng ngày" },
    usageEvents: { en: "Usage event names", vi: "Tên sự kiện sử dụng" },
    billingSummary: { en: "Billing contract summary", vi: "Tóm tắt ràng buộc thanh toán" },
    operationalContext: { en: "Operational context", vi: "Bối cảnh vận hành" },
    and: { en: "and", vi: "và" },
    themeApplied: { en: "with theme set to", vi: "với giao diện đang dùng là" },
    usedToday: { en: "call minutes used today.", vi: "phút gọi đã dùng hôm nay." },
    billingAwareEvents: {
      en: "billing-aware provider events are now locked.",
      vi: "các sự kiện provider gắn với thanh toán hiện đã được khóa.",
    },
    appId: { en: "App ID", vi: "Mã ứng dụng" },
    billingCycle: { en: "Billing cycle", vi: "Chu kỳ thanh toán" },
    expiresAt: { en: "Expires at", vi: "Hết hạn lúc" },
    subscriptionVisibility: { en: "Subscription visibility", vi: "Mức hiển thị gói" },
    betaGateReason: { en: "Beta gate reason", vi: "Lý do của cổng beta" },
    remainingToday: { en: "Remaining today", vi: "Còn lại hôm nay" },
    minutes: { en: "minutes", vi: "phút" },
    unreadNotifications: { en: "Unread notifications", vi: "Thông báo chưa đọc" },
    pendingProofs: { en: "Pending proofs", vi: "Bằng chứng đang chờ duyệt" },
    aiActions: { en: "AI actions", vi: "Hành động AI" },
    trustBand: { en: "Trust band", vi: "Mức niềm tin" },
    subscriptionVisibilityFull: { en: "full visibility", vi: "hiển thị đầy đủ" },
    subscriptionVisibilityLimited: { en: "limited visibility", vi: "hiển thị giới hạn" },
    betaGateUnlocked: { en: "Unlocked", vi: "Đã mở" },
    betaGateLocked: { en: "Locked", vi: "Đang khóa" },
    betaGateReasonEligible: { en: "eligible", vi: "đủ điều kiện" },
    betaGateReasonPlanNotEligible: { en: "plan not eligible", vi: "gói chưa đủ điều kiện" },
    betaGateReasonSubscriptionInactive: { en: "subscription inactive", vi: "gói chưa hoạt động" },
    trustBandHealthy: { en: "healthy", vi: "ổn định" },
    trustBandGrowth: { en: "growth", vi: "đang tăng" },
    trustBandCritical: { en: "critical", vi: "cần chú ý" },
    subscriptionStatusActive: { en: "active", vi: "đang hoạt động" },
    subscriptionStatusTrialing: { en: "trialing", vi: "đang dùng thử" },
    billingCycleMonthly: { en: "monthly", vi: "hằng tháng" },
    billingCycleYearly: { en: "yearly", vi: "hằng năm" },
  },
  preferencesFlow: {
    title: { en: "Preferences update flow", vi: "Luồng cập nhật tùy chọn" },
    summaryPrefix: {
      en: "Subscription visibility follows beta gate:",
      vi: "Mức hiển thị gói phụ thuộc vào cổng beta:",
    },
    full: { en: "full visibility", vi: "hiển thị đầy đủ" },
    limited: { en: "limited visibility", vi: "hiển thị giới hạn" },
    language: { en: "Language", vi: "Ngôn ngữ" },
    theme: { en: "Theme", vi: "Giao diện" },
    emailNotifications: { en: "Email notifications", vi: "Thông báo email" },
    pushNotifications: { en: "Push notifications", vi: "Thông báo đẩy" },
    save: { en: "Save preferences contract", vi: "Lưu tùy chọn" },
    saving: { en: "Saving...", vi: "Đang lưu..." },
    success: {
      en: "Preferences contract update completed.",
      vi: "Đã hoàn tất cập nhật tùy chọn.",
    },
    failure: {
      en: "Unable to update preferences contract.",
      vi: "Không thể cập nhật tùy chọn.",
    },
  },
  providerRoutingStatus: {
    title: { en: "Provider routing snapshot", vi: "Ảnh chụp nhanh định tuyến nhà cung cấp" },
    source: { en: "Provider source", vi: "Nguồn nhà cung cấp" },
    apiLive: { en: "API live", vi: "API trực tiếp" },
    snapshotFallback: {
      en: "snapshot fallback",
      vi: "phương án dự phòng từ ảnh chụp nhanh",
    },
    registry: { en: "Provider registry", vi: "Danh mục nhà cung cấp" },
    lastSynced: { en: "Last synced", vi: "Đồng bộ lúc" },
    none: { en: "none", vi: "không có" },
    fallback: { en: "fallback", vi: "dự phòng" },
    score: { en: "score", vi: "điểm số" },
    refreshFailure: {
      en: "Unable to refresh provider routing from API.",
      vi: "Không thể làm mới định tuyến nhà cung cấp từ API.",
    },
  },
} as const;
